SocialNetwork/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using SocialNetwork.Models;

namespace SocialNetwork.Controllers
{
    public class HomeController : Controller
    {
        private Database1Entities1 db = new Database1Entities1();
        // GET: Home
        public ActionResult Index()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            User user = db.Users.Find(Int32.Parse(Session["UserID"].ToString()));
            Profile profile = db.Profiles.Where(x => x.UserId == user.Id).FirstOrDefault();

            ViewBag.my = true;
            ViewBag.UserId = user.Id;
            ViewBag.profileid = profile.Id;
            ViewBag.ProfileName = profile.FirstName;
            ViewBag.ProfileSurName = profile.LastName;
            ViewBag.image = db.Files.Find(user.AvatarID).Url;
            return View(user.Posts.Reverse());
        }

        [HttpPost]
        public ActionResult Index(int id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            User user = db.Users.Find(id);
            Profile profile = db.Profiles.Where(x => x.UserId == user.Id).FirstOrDefault();

            ViewBag.my = false;
            ViewBag.UserId = user.Id;
            ViewBag.profileid = profile.Id;
            ViewBag.ProfileName = profile.FirstName;
            ViewBag.ProfileSurName = profile.LastName;
            ViewBag.image = db.Files.Find(user.AvatarID).Url;
            return View(user.Posts.Reverse());
        }


        public ActionResult search(string name)
        {
            if (Session["UserID"] == null)
                return HttpNotFound();

            int id = int.Parse(Session["UserID"].ToString());
            ViewBag.userID = id; 
            List<Profile> pfs = db.Profiles.Where(i => i.FirstName.Contains(name) || i.LastName.Contains(name)).ToList();
            Profile me = pfs.Where(i => i.UserId == id).FirstOrDefault();
            if (me != null)
                pfs.Remove(me);

            List<User> users = new List<Models.User>();            

            foreach (var item in pfs)
            {
                if(db.FriendRelations.Where(i => (i.UserId1 == id && i.UserId2 == item.User.Id) 
                        || (i.UserId1 == item.User.Id && i.UserId2 == id) ).Count() == 0 )
                {

                        users.Add(item.User);   
                }
                    
            }

            return View(users);
        }

        public ActionResult friends()
        {

            if (Session["UserID"] == null)
                return RedirectToAction("Index", "Home");

            int id = int.Parse(Session["UserID"].ToString());
            ViewBag.UserId = id;

            var arr = db.FriendRelations.Where(k => k.UserId1 == id || k.UserId2 == id);

            List<User> friendlist = new List<Models.User>();
            foreach (var item in arr)
            {
                if(item.UserId1 != id)
                    friendlist.Add(db.Users.Find(item.UserId1));
                if (item.UserId2 != id)
                    friendlist.Add(db.Users.Find(item.UserId2));
            }
            User me = friendlist.Where(i => i.Id == id).FirstOrDefault(); ;
            if (me != null)
                friendlist.Remove(me);


            List<User> rlist = new List<Models.User>();// new List<FriendRequest>(); 
            var arr2 = db.FriendRequests.Where(i => i.user2 == id).ToList();

            foreach (var item in arr2)
            {
                rlist.Add(db.Users.Find(item.user1));
            }

            return View(new Tuple<List<User>, List<User> >(friendlist, rlist));
        }

        public ActionResult addToFriend(int id)
        {
            int myid = int.Parse(Session["UserID"].ToString());

            FriendRequest check = db.FriendRequests.Where(i => i.user1 == id).FirstOrDefault(); ;

            if(check != null)
            {
                db.FriendRequests.Remove(check);
                db.SaveChanges();

                FriendRelation fr = new FriendRelation();
                fr.UserId1 = myid;
                fr.UserId2 = id;
                db.FriendRelations.Add(fr);
                db.SaveChanges();
                return RedirectToAction("friends", "Home");
            }

            FriendRequest r = new FriendRequest();
            r.user1 = myid;
            r.user2 = id;

            db.FriendRequests.Add(r);
            db.SaveChanges();

            return RedirectToAction("friends", "Home");
        }


        public ActionResult sendMessage(int id, string name)
        {
            int userid = int.Parse(Session["UserID"].ToString()); 
            
            var tmp = db.ConvUsers.Where(i => i.UserId == userid);
            var tmp2 = tmp.Where(i => i.UserId == id);
            foreach (var item in tmp)
            {
                foreach (var item2 in tmp2)
                {
                    if (item.Id == item2.Id)
                        return RedirectToAction("index", "Conversations");
                }
            }

            Profile me = db.Profiles.Where(i => i.UserId == userid).FirstOrDefault();

            Conversation newc = new Conversation();
            newc.Name = name + "--" +me.FirstName;
            db.Conversations.Add(newc);
            db.SaveChanges();
            ConvUser newcu = new ConvUser();
            newcu.ConvId = newc.Id;
            newcu.UserId = id;
            ConvUser newcu2 = new ConvUser();
            newcu2.ConvId = newc.Id;
            newcu2.UserId = userid;
            db.ConvUsers.Add(newcu);
            db.ConvUsers.Add(newcu2);
            db.SaveChanges();

            return RedirectToAction("index", "Conversations");
        }


    }
}

SocialNetwork/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialNetwork.Models;
using System.Data;
using System.Data.Entity;

namespace SocialNetwork.Controllers
{
    public class PostsController : Controller
    {
        private Database1Entities1 db = new Database1Entities1();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post)
        {
            if (ModelState.IsValid)
            {
                post.UserId = int.Parse(Session["UserID"].ToString());
                db.Posts.Add(post);
                db.SaveChanges();
            }
            return RedirectToAction("Index","Home");
        }

    }
}

SocialNetwork/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialNetwork.Models;
using System.Data;
using System.Data.Entity;
using System.Net;
using SocialNetwork.Controllers;

namespace SocialNetwork.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile
        private Database1Entities1 db = new Database1Entities1();
        public ActionResult Create()
        {
            if (ModelState.IsValid)
            {
               
                Profile profile = new Models.Profile();
                profile.UserId = Int32.Parse(Session["UserId"].ToString());
                profile.FirstName = "Your Name";
                profile.LastName = "Your last name";
                profile.gender = "male";
                profile.BirthDate = new DateTime().Date;
                db.Profiles.Add(profile);
                db.SaveChanges();
                return RedirectToAction("index", "Home");
            }

            return View();
        }
       

        public ActionResult Edit(int? uId)
        {
            if (Session["UserID"] != null)
            {
                if (uId == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                if (int.Parse(Session["UserID"].ToString()) != uId)
                {
                    return HttpNotFound();
                }
                Profile profile = db.Profiles.Where(x => x.UserId == uId).FirstOrDefault();
                if (profile == null)
                {
                    return HttpNotFound();
                }
                return View(profile);
            }
            return HttpNotFound();

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Profile profile)
        {
            if (ModelState.IsValid)
            {
                profile.UserId = Int32.Parse(Session["UserId"].ToString());
                db.Entry(profile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(profile);
        }
    }
}

SocialNetwork/Views/Home/Index.cshtml
@model IEnumerable<SocialNetwork.Models.Post>

@{
    ViewBag.Title = "Index";
}


<div class="row">
    <div class="col s3">

        <img src="@ViewBag.image" class="avatar materialboxed" />
        <h3>@ViewBag.ProfileName</h3>
        <h3>@ViewBag.ProfileSurName</h3>

        @if (ViewBag.my == true)
        {
            using (Ajax.BeginForm("Edit", "Profile", new { uId = ViewBag.UserId }, new AjaxOptions
            {
                HttpMethod = "Get",
                UpdateTargetId = "results2",
                LoadingElementDuration = 1000
            }))
            {
                <p>
                    <input type="submit" value="Edit" />
                </p>
            }
            <div id="results2">

            </div>
        }
        else
        {
           @Html.ActionLink("send Message", "sendMessage", new {id = ViewBag.UserId, name = ViewBag.ProfileName })
        }

        <hr />

    </div>

    <div class="col s9">

        @if (ViewBag.my)
        {
            using (Ajax.BeginForm("Create", "Posts", new AjaxOptions
            {
                HttpMethod = "Get",
                UpdateTargetId = "results",
                LoadingElementDuration = 1000
            }))
            {

                <p>
                    <input type="submit" value="add new Post" />
                </p>
            }

            <div id="results">

            </div>
        }
        

        <div class="container" style="width:auto">

            @foreach (var item in Model)
            {
                <div class="row">
                    <div class="col s12 ">
                        <div class="card blue-grey darken-1">
                            <div class="card-content white-text">
                                <span class="card-title">@item.Title</span>
                                <p style="white-space: pre-line">
                                    @item.Text<br />
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            }


            <div class="row">
                <div class="col s12">
                    <div class="card-panel">
                        <span class="blue-text text-darken-2">Welcome to my site</span>
                    </div>
                </div>
            </div>


        </div>

    </div>

</div>





<script >
    $(document).ready(function () {
        $('.materialboxed').materialbox();
    });
</script>

<script src="~/Scripts/jquery-2.2.3.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>




SocialNetwork/Views/Home/friends.cshtml
@model Tuple< List<SocialNetwork.Models.User>,List<SocialNetwork.Models.User> >  



<div class="row">
    <div class="col s3" style="height:1000px">
        <h5> Friend requests</h5>
        @foreach (var item in Model.Item2)
        {
            <div class="row">
                <div class="col s9">
                    <p>
                        @item.Profiles.First().FirstName 
                        @item.Profiles.First().LastName
                    </p>
                </div>
                <div class="col s3">
                    <p>
                         @Html.ActionLink("add", "addToFriend", new { id = item.Id })
                    </p>
                </div>
            </div>
                       
            <hr />
        }
    </div>

    <div class="col s6">
        @using (Ajax.BeginForm("search", new AjaxOptions
        {
            UpdateTargetId = "friendlist",
            LoadingElementDuration = 1000
        }))
        {
            <p>
                <input name="name" type="text"/>
                <input type="submit" value="search internet" />
            </p>
        }

        <div id="friendlist">
           
        </div>

        <h5>Friend List</h5>

        @if (Model.Item1.Count == 0)
        {
            <h6>you friend list is empty</h6>
        }
        @foreach (var item in Model.Item1)
            {
            <table>
                <tr>

                    <td>
                        <img src="/../@item.File.Url" style="width:100px" />
                    </td>
                    <td> <h4>@item.Profiles.First().FirstName @item.Profiles.First().LastName </h4> </td>

                    <td>
                        @using(Html.BeginForm("Index", "Home",FormMethod.Post)) 
                        { 
                            <input name="id" value="@item.Id" hidden />  
                            <input type="submit" value="open" />  
                            
                        } 
                    </td>

                   

                </tr>
            </table>

        }
    </div>


</div>

<script src="~/Scripts/jquery-2.2.3.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

SocialNetwork/Views/Home/search.cshtml
@model IEnumerable<SocialNetwork.Models.User>

@{
    Layout = null;
}


    <h5>Search result</h5>    
    <table class="table">
        <tr>
            <th>
                avatar
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Profiles.First().FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Profiles.First().LastName)
            </th>
            <th></th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr style="background-color:#f48fb1; padding:10px">
            <td>
                <img src="/../@item.File.Url" style="width:100px" />

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Profiles.First().FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Profiles.First().LastName)
            </td>
            <td>
               
                @Html.ActionLink("add to friends", "addToFriend", new { id = item.Id });
            </td>

            

        </tr>
    }
    
    </table>


